### ISSUE TITLE
Naming issue with URI

### ISSUE THREAD

**Issue by meyt** [Carrene/restfulpy#111]
There are many confusion on the naming of [URL/URI](https://www.w3.org/TR/uri-clarification/#confusion). but actually this is [URL](https://github.com/zzzeek/sqlalchemy/blob/55b511c3960cad636ff1e512594368a36a85ce5c/lib/sqlalchemy/engine/url.py#L30]=) used in connection strings, and [restfulpy using URI](https://github.com/Carrene/restfulpy/search?utf8=%E2%9C%93&q=uri&type=).

**Comment by pylover** [comment]
Mmmm, yes, I swear that, the old sqlalchemy's documentation is using `URI` instead of the `URL`
