### ISSUE TITLE
Name correction for mixins

### ISSUE THREAD

**Issue by meyt** [Carrene/restfulpy#115]
As what i saw before, `mixins` is correct, not [mixines](https://github.com/Carrene/restfulpy/blob/master/restfulpy/orm/mixines.py).

**Comment by pylover** [comment]
Thank's a lot. Such a ridiculous mistake.

An incompatible release is coming. What you suggest to do.
1. Keeping the old module with a warning for compatibility.
2. Don't care about the compatibility and rollup an incompatible release?

**Comment by meyt** [comment]
i don't think it's good idea to keep old module, let restfulpy moving fast forward.
