### ISSUE TITLE
Documentation problem with hybrid property

### ISSUE THREAD

**Issue by meyt** [Carrene/restfulpy#126]
I think there is problem with documentation generator, sqlalchemy hybrid property type is `<class 'sqlalchemy.orm.attributes.create_proxied_attribute.<locals>.Proxy'>` and doesn't have [`python_type`](https://github.com/Carrene/restfulpy/blob/411d16e006d28a9e73fc2dcebae3d2402b89bb7c/restfulpy/testing/documentation.py#L149). So models with hybrid property occure errors on generating documents.

**Comment by pylover** [comment]
The documentary system is completely removed in #163 
You may use [Carrene/bddrest](https://github.com/Carrene/bddrest) instead
