### ISSUE TITLE
ISO Time format, Deprecated! 

### ISSUE THREAD

**Issue by pylover** [Carrene/restfulpy#131]
By @maryayi 

I have no functional problem about dates yet but I get a warning about deprecation of time format you're sending through API in near future from MomentJS.

Please check and fix this if needed:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. 
moment construction falls back to js Date(), which is not reliable across all browsers and versions. 
Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. 
Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
```

**Comment by pylover** [comment]
@maryayi , @mrastiak , Please tell us to know what format you are interested?

**Comment by memlucky71** [comment]
@maryayi ISO time format is not deprecated. I converted some dates the backend generates and the MomentJS could parse it. Please specify what was the string you tried to parse with MomentJS.

**Comment by maryayi** [comment]
@memlucky71 Yes... that's right. ISO time format is not deprecated! 
That warning was a bug in Vue when we add Moment with `use` method  and now I fixed it in project Nandy. thanks

**Comment by memlucky71** [comment]
So this issue is closed.
