### ISSUE TITLE
"with_lockmode" deprecated by sqlalchemy

### ISSUE THREAD

**Issue by mahdi13** [Carrene/restfulpy#146]
This line has been deprecated (based on http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.with_lockmode):

https://github.com/Carrene/restfulpy/blob/28289730af1a7d7712ef788075eed3554c2cf67c/restfulpy/taskqueue.py#L52

I think this would be a better replace:
```
        .with_for_update()
```

**Comment by pylover** [comment]
Nice.  Thanks
