### ISSUE TITLE
Independent timezone usage

### ISSUE THREAD

**Issue by meyt** [Carrene/restfulpy#169]
All datetime usages need to be system-indepndent on timezone. (`datetime.now` -> `datetime.utcnow`)

**Comment by pylover** [comment]
I think it's ok to add a config value to indicate using system's local timezone or not.

Thoughts?

**Comment by meyt** [comment]
i don't know why database designers allow us to specify timezone 😂

**Comment by pylover** [comment]
So?

**Comment by meyt** [comment]
Configurable value seems no sense here. UTC is very common in RESTful API communications, and timezone converting should happen on user representation layer. be a `benevolent dictator` 😇

**Comment by pylover** [comment]
A best practice for the timezone is to set it per user. in this case, the configuration value will be set to a default timezone for example: (as you want) UTC.

But when we need a timezone for all users, we can put it simply in the configuration file.

I think we have to use this configuration value at all to preserve the compatibility. we have to care about the projects that already using the restfully.

It helps us to prevent a broken and hateful release!

**Comment by pylover** [comment]
I have to write some tests for:

### Time zone aware mode
The application is configured to use UTC or another time zone:

* Submit without timezone: accept and assume as the configured timezone
* Submit with `Z`: accept and assume as the UTC, so we have to convert it to configured timezone if desired.
* Submit with `+3:30`: convert to configured timezone and continue the rest of process

### Naive mode
The application is configured to use server's local date and time.
 
* Submit without timezone: accept and assume the local date and time.
* Submit with 'Z': accept and assume as the UTC, so we have to convert it to local date and time before continuing the rest of process
* Submit with '+3:30': accept and convert it to appropriate local date and time.

**Comment by pylover** [comment]
@meyt ?

**Comment by meyt** [comment]
Ouh, it's not actually what i mean for, sorry my bad.
actually `restfuly.orm.mixins` using `datetime.now` for store datetimes, and its the reason for invalid data on different environments that serve our application.

**Comment by pylover** [comment]
Ok, after these changes, current time capturing should depend on the configured timezone.
